### ISSUE TITLE
install.sh doesn't work with Apple ARM chip

### ISSUE THREAD

**Issue by svenrdz** [kitagry/asyncomplete-tabnine.vim#11]
I think the urls to get the version number and binaries in `install.sh` are outdated, and at the same time there was a recent update to add support for Apple's M1 chip.

There's an updated version of the download script in the official vim repo: https://github.com/codota/tabnine-vim/blob/master/dl_binaries.sh

For it to work, I've also added in `s:parse_architecture` these lines, to account for the fact that `system` seems to give `arm64` instead of `aarch64`, as used in the tabnine binaries:
```vim
    if l:system =~ 'arm64'
        return 'aarch64'
    endif
```

**Comment by kitagry** [comment]
Thank you for the report!
I'll fix it this weekend.

**Comment by kitagry** [comment]
@svenrdz 
I think it was resolved in #12. But, I don't have M1 Mac. Would you try #12?

**Comment by svenrdz** [comment]
@kitagry There's a typo in `s:parse_macos_architecture()`, after fixing it locally it installs the binaries as expected 👍 

```vim
@@ -178,7 +180,7 @@ function! s:parse_macos_architecture() abort
     let l:system = system('uname -m')
     if  l:system =~ 'x86-64' || l:system =~ 'x86_64'
         return 'x86_64'
-    elseif l:system =! 'arm64'  " m1 mac
+    elseif l:system =~ 'arm64'  " m1 mac
         return 'aarch64'
     endif
 endfunction
```

**Comment by kitagry** [comment]
Oh, it is easy mistake. Thank you.

**Comment by kitagry** [comment]
Thanks for your cooperation!
